let counter = 0;

/**
 * Generates a unique numeric ID. the ID is generated by incrementing a counter.
 * Each call of this function returns a number one higher than the previous call.
 * So, the same number can't be returned twice unless the counter exceeds its bounds.
 *
 * @returns {number} A unique numeric ID.
 */
export default function uid() {
    return counter++;
}