export default {
    ADD_EQUATION: "ADD_EQUATION",
    DELETE_EQUATION: "DELETE_EQUATION",
    LOAD_EQUATIONS: "LOAD_EQUATIONS",
    UPDATE_EQUATION: "UPDATE_EQUATION",

    ADD_PARAM: "ADD_PARAM",
    DELETE_PARAM: "DELETE_PARAM",
    LOAD_PARAMS: "LOAD_PARAMS",
    UPDATE_PARAM: "UPDATE_PARAM",

    LOAD_PROJECTS: "LOAD_PROJECTS",

    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",

    SET_TIME: "SET_TIME",
    SET_RESOLUTION: "SET_RESOLUTION",

    LOAD_PROJECT: "LOAD_PROJECT"
};