export default {
    ADD_EQUATION: "ADD_EQUATION",
    DELETE_EQUATION: "DELETE_EQUATION",
    LOAD_EQUATIONS: "LOAD_EQUATIONS",
    UPDATE_EQUATION: "UPDATE_EQUATION",

    MINIMIZE_SIDEBAR: "MINIMIZE_SIDEBAR",
    MAXIMIZE_SIDEBAR: "MAXIMIZE_SIDEBAR"
};